const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.video,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.ScriptsInEvents["01-3_Event10"],
		C3.ScriptsInEvents["01-3_Event12"],
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.ScriptsInEvents["02-3_Event3"],
		C3.ScriptsInEvents["02-5_Event13"],
		C3.ScriptsInEvents["02-7_Event16"],
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{button_home: 0},
	{button_que: 0},
	{button_book: 0},
	{buttonsound_01: 0},
	{buttonsound_02: 0},
	{no: 0},
	{淡入淡出: 0},
	{next: 0},
	{play: 0},
	{nono: 0},
	{button3: 0},
	{button4: 0},
	{button5: 0},
	{button6: 0},
	{button7: 0},
	{b8: 0},
	{b9: 0},
	{b10: 0},
	{b11: 0},
	{字幕2: 0},
	{字幕1: 0},
	{字幕3: 0},
	{字幕18: 0},
	{字幕23: 0},
	{字幕25: 0},
	{eight: 0},
	{five: 0},
	{four: 0},
	{nine: 0},
	{one: 0},
	{seven: 0},
	{three: 0},
	{two: 0},
	{six: 0},
	{拖放: 0},
	{上大靜脈: 0},
	{下大靜脈: 0},
	{主動脈: 0},
	{右心室: 0},
	{右心房: 0},
	{左心室: 0},
	{左心房: 0},
	{瓣膜: 0},
	{肺動脈: 0},
	{肺靜脈: 0},
	{配對題: 0},
	{配對題頁面: 0},
	{blank1: 0},
	{blank2: 0},
	{blank3: 0},
	{blank4: 0},
	{blank5: 0},
	{blank6: 0},
	{blank7: 0},
	{blank8: 0},
	{blank9: 0},
	{blank10: 0},
	{英_上大靜脈: 0},
	{英_下大靜脈: 0},
	{英_主動脈: 0},
	{英_右心室: 0},
	{英_右心房: 0},
	{英_左心室: 0},
	{英_左心房: 0},
	{英_瓣膜: 0},
	{英_肺動脈: 0},
	{英_肺靜脈: 0},
	{配對go: 0},
	{配對top: 0},
	{配對英文背景: 0},
	{句子框: 0},
	{系統聆聽按鍵: 0},
	{重組: 0},
	{重組bg: 0},
	{重組top: 0},
	{重組說明: 0},
	{重組選項4: 0},
	{重組題目1: 0},
	{重組5: 0},
	{重組選項2: 0},
	{重組選項3: 0},
	{重組選項1: 0},
	{Sprite13: 0},
	{健身心臟: 0},
	{心臟跑步: 0},
	{搔頭心臟: 0},
	{back: 0},
	{video1: 0},
	{Touch: 0},
	{video2: 0},
	{bg: 0},
	{Sprite: 0},
	{cover: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{音頻: 0},
	{knowledge: 0},
	{視頻: 0},
	{Sprite5: 0},
	{視頻2: 0},
	{Sprite6: 0},
	{視頻3: 0},
	{Sprite9: 0},
	{視頻4: 0},
	{視頻5: 0},
	{視頻6: 0},
	{Sprite10: 0},
	{開始課程: 0},
	{複習: 0},
	{測驗: 0},
	{操作說明: 0},
	{電子書操作說明: 0},
	{Sprite8: 0},
	{letsgo: 0},
	{線條: 0},
	{雙線條: 0},
	{Train_text: 0},
	{train: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite14: 0},
	{選擇題: 0},
	{button_nextQ: 0},
	{半透明背景: 0},
	{Sprite16: 0},
	{右心房標示: 0},
	{左心房標示: 0},
	{Sprite15: 0},
	{右心室標示: 0},
	{左心室標示: 0},
	{場景5右心房: 0},
	{場景10血管: 0},
	{動脈螢光: 0},
	{靜脈螢光: 0},
	{靜脈: 0},
	{微血管: 0},
	{動脈: 0},
	{場景三字幕: 0},
	{看vr: 0},
	{查看動脈vr: 0},
	{微血管vr查看: 0},
	{靜脈vr觀看: 0},
	{移動放大鏡: 0},
	{人: 0},
	{放大鏡: 0},
	{血壓: 0},
	{紅血球: 0},
	{紅血球特徵1: 0},
	{紅血球特徵2: 0},
	{紅血球特徵3: 0},
	{紅血球特徵4: 0},
	{白血球: 0},
	{白血球特徵1: 0},
	{白血球特徵2: 0},
	{白血球特徵3: 0},
	{白血球特徵4: 0},
	{看生病血液: 0},
	{字幕27: 0},
	{血小板特徵1: 0},
	{血小板: 0},
	{血小板特徵3: 0},
	{血小板特徵4: 0},
	{字幕29: 0},
	{使用說明添加英文音檔: 0},
	{valves: 0},
	{p19後方圓形: 0},
	{選擇說明: 0},
	{選擇背景: 0},
	{選擇題目: 0},
	{閃爍: 0},
	{選擇1選項: 0},
	{選擇1選項3: 0},
	{選擇1選項2: 0},
	{剖面心臟: 0},
	{選擇說明2: 0},
	{Q1_obj: 0},
	{chooses: 0},
	{Q2_num: 0},
	{配對完成: 0},
	{選擇完成: 0},
	{重組句子完成: 0},
	{影片暫停: 0}
];

self.InstanceType = {
	button_home: class extends self.ISpriteInstance {},
	button_que: class extends self.ISpriteInstance {},
	button_book: class extends self.ISpriteInstance {},
	buttonsound_01: class extends self.ISpriteInstance {},
	buttonsound_02: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	nono: class extends self.ISpriteInstance {},
	button3: class extends self.ISpriteInstance {},
	button4: class extends self.ISpriteInstance {},
	button5: class extends self.ISpriteInstance {},
	button6: class extends self.ISpriteInstance {},
	button7: class extends self.ISpriteInstance {},
	b8: class extends self.ISpriteInstance {},
	b9: class extends self.ISpriteInstance {},
	b10: class extends self.ISpriteInstance {},
	b11: class extends self.ISpriteInstance {},
	字幕2: class extends self.ISpriteInstance {},
	字幕1: class extends self.ISpriteInstance {},
	字幕3: class extends self.ISpriteInstance {},
	字幕18: class extends self.ISpriteInstance {},
	字幕23: class extends self.ISpriteInstance {},
	字幕25: class extends self.ISpriteInstance {},
	eight: class extends self.ISpriteInstance {},
	five: class extends self.ISpriteInstance {},
	four: class extends self.ISpriteInstance {},
	nine: class extends self.ISpriteInstance {},
	one: class extends self.ISpriteInstance {},
	seven: class extends self.ISpriteInstance {},
	three: class extends self.ISpriteInstance {},
	two: class extends self.ISpriteInstance {},
	six: class extends self.ISpriteInstance {},
	上大靜脈: class extends self.ISpriteInstance {},
	下大靜脈: class extends self.ISpriteInstance {},
	主動脈: class extends self.ISpriteInstance {},
	右心室: class extends self.ISpriteInstance {},
	右心房: class extends self.ISpriteInstance {},
	左心室: class extends self.ISpriteInstance {},
	左心房: class extends self.ISpriteInstance {},
	瓣膜: class extends self.ISpriteInstance {},
	肺動脈: class extends self.ISpriteInstance {},
	肺靜脈: class extends self.ISpriteInstance {},
	配對題: class extends self.ISpriteInstance {},
	配對題頁面: class extends self.ISpriteInstance {},
	blank1: class extends self.ISpriteInstance {},
	blank2: class extends self.ISpriteInstance {},
	blank3: class extends self.ISpriteInstance {},
	blank4: class extends self.ISpriteInstance {},
	blank5: class extends self.ISpriteInstance {},
	blank6: class extends self.ISpriteInstance {},
	blank7: class extends self.ISpriteInstance {},
	blank8: class extends self.ISpriteInstance {},
	blank9: class extends self.ISpriteInstance {},
	blank10: class extends self.ISpriteInstance {},
	英_上大靜脈: class extends self.ISpriteInstance {},
	英_下大靜脈: class extends self.ISpriteInstance {},
	英_主動脈: class extends self.ISpriteInstance {},
	英_右心室: class extends self.ISpriteInstance {},
	英_右心房: class extends self.ISpriteInstance {},
	英_左心室: class extends self.ISpriteInstance {},
	英_左心房: class extends self.ISpriteInstance {},
	英_瓣膜: class extends self.ISpriteInstance {},
	英_肺動脈: class extends self.ISpriteInstance {},
	英_肺靜脈: class extends self.ISpriteInstance {},
	配對go: class extends self.ISpriteInstance {},
	配對top: class extends self.ISpriteInstance {},
	配對英文背景: class extends self.ISpriteInstance {},
	句子框: class extends self.ISpriteInstance {},
	系統聆聽按鍵: class extends self.ISpriteInstance {},
	重組: class extends self.ISpriteInstance {},
	重組bg: class extends self.ISpriteInstance {},
	重組top: class extends self.ISpriteInstance {},
	重組說明: class extends self.ISpriteInstance {},
	重組選項4: class extends self.ISpriteInstance {},
	重組題目1: class extends self.ISpriteInstance {},
	重組5: class extends self.ISpriteInstance {},
	重組選項2: class extends self.ISpriteInstance {},
	重組選項3: class extends self.ISpriteInstance {},
	重組選項1: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	健身心臟: class extends self.ISpriteInstance {},
	心臟跑步: class extends self.ISpriteInstance {},
	搔頭心臟: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	video1: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	video2: class extends self.IWorldInstance {},
	bg: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	cover: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	knowledge: class extends self.ISpriteInstance {},
	視頻: class extends self.IWorldInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	視頻2: class extends self.IWorldInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	視頻3: class extends self.IWorldInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	視頻4: class extends self.IWorldInstance {},
	視頻5: class extends self.IWorldInstance {},
	視頻6: class extends self.IWorldInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	開始課程: class extends self.ISpriteInstance {},
	複習: class extends self.ISpriteInstance {},
	測驗: class extends self.ISpriteInstance {},
	操作說明: class extends self.ISpriteInstance {},
	電子書操作說明: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	letsgo: class extends self.ISpriteInstance {},
	線條: class extends self.ISpriteInstance {},
	雙線條: class extends self.ISpriteInstance {},
	Train_text: class extends self.ISpriteInstance {},
	train: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	選擇題: class extends self.ISpriteInstance {},
	button_nextQ: class extends self.ISpriteInstance {},
	半透明背景: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	右心房標示: class extends self.ISpriteInstance {},
	左心房標示: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	右心室標示: class extends self.ISpriteInstance {},
	左心室標示: class extends self.ISpriteInstance {},
	場景5右心房: class extends self.ISpriteInstance {},
	場景10血管: class extends self.ISpriteInstance {},
	動脈螢光: class extends self.ISpriteInstance {},
	靜脈螢光: class extends self.ISpriteInstance {},
	靜脈: class extends self.ISpriteInstance {},
	微血管: class extends self.ISpriteInstance {},
	動脈: class extends self.ISpriteInstance {},
	場景三字幕: class extends self.ISpriteInstance {},
	看vr: class extends self.ISpriteInstance {},
	查看動脈vr: class extends self.ISpriteInstance {},
	微血管vr查看: class extends self.ISpriteInstance {},
	靜脈vr觀看: class extends self.ISpriteInstance {},
	移動放大鏡: class extends self.ISpriteInstance {},
	人: class extends self.ISpriteInstance {},
	放大鏡: class extends self.ISpriteInstance {},
	血壓: class extends self.ISpriteInstance {},
	紅血球: class extends self.ISpriteInstance {},
	紅血球特徵1: class extends self.ISpriteInstance {},
	紅血球特徵2: class extends self.ISpriteInstance {},
	紅血球特徵3: class extends self.ISpriteInstance {},
	紅血球特徵4: class extends self.ISpriteInstance {},
	白血球: class extends self.ISpriteInstance {},
	白血球特徵1: class extends self.ISpriteInstance {},
	白血球特徵2: class extends self.ISpriteInstance {},
	白血球特徵3: class extends self.ISpriteInstance {},
	白血球特徵4: class extends self.ISpriteInstance {},
	看生病血液: class extends self.ISpriteInstance {},
	字幕27: class extends self.ISpriteInstance {},
	血小板特徵1: class extends self.ISpriteInstance {},
	血小板: class extends self.ISpriteInstance {},
	血小板特徵3: class extends self.ISpriteInstance {},
	血小板特徵4: class extends self.ISpriteInstance {},
	字幕29: class extends self.ISpriteInstance {},
	使用說明添加英文音檔: class extends self.ISpriteInstance {},
	valves: class extends self.ISpriteInstance {},
	p19後方圓形: class extends self.ISpriteInstance {},
	選擇說明: class extends self.ISpriteInstance {},
	選擇背景: class extends self.ISpriteInstance {},
	選擇題目: class extends self.ISpriteInstance {},
	選擇1選項: class extends self.ISpriteInstance {},
	選擇1選項3: class extends self.ISpriteInstance {},
	選擇1選項2: class extends self.ISpriteInstance {},
	剖面心臟: class extends self.ISpriteInstance {},
	選擇說明2: class extends self.ISpriteInstance {},
	Q1_obj: class extends self.ISpriteInstance {},
	chooses: class extends self.ISpriteInstance {}
}